/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserDashboardRouteImport } from './routes/userDashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserDashboardLeaveHistoryRouteImport } from './routes/userDashboard.leaveHistory'
import { Route as UserDashboardLeaveFormRouteImport } from './routes/userDashboard.leaveForm'
import { Route as AdminAdminDashboardRouteImport } from './routes/admin/adminDashboard'
import { Route as AdminAdminDashboardPanelRouteImport } from './routes/admin/adminDashboard.panel'
import { Route as AdminAdminDashboardNewEmployeesRouteImport } from './routes/admin/adminDashboard.newEmployees'
import { Route as AdminAdminDashboardLeavesRouteImport } from './routes/admin/adminDashboard.leaves'
import { Route as AdminAdminDashboardEmployeesRouteImport } from './routes/admin/adminDashboard.employees'

const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/userDashboard',
  path: '/userDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardLeaveHistoryRoute =
  UserDashboardLeaveHistoryRouteImport.update({
    id: '/leaveHistory',
    path: '/leaveHistory',
    getParentRoute: () => UserDashboardRoute,
  } as any)
const UserDashboardLeaveFormRoute = UserDashboardLeaveFormRouteImport.update({
  id: '/leaveForm',
  path: '/leaveForm',
  getParentRoute: () => UserDashboardRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/adminDashboard',
  path: '/admin/adminDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminDashboardPanelRoute =
  AdminAdminDashboardPanelRouteImport.update({
    id: '/panel',
    path: '/panel',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardNewEmployeesRoute =
  AdminAdminDashboardNewEmployeesRouteImport.update({
    id: '/newEmployees',
    path: '/newEmployees',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardLeavesRoute =
  AdminAdminDashboardLeavesRouteImport.update({
    id: '/leaves',
    path: '/leaves',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardEmployeesRoute =
  AdminAdminDashboardEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/userDashboard': typeof UserDashboardRouteWithChildren
  '/admin/adminDashboard': typeof AdminAdminDashboardRouteWithChildren
  '/userDashboard/leaveForm': typeof UserDashboardLeaveFormRoute
  '/userDashboard/leaveHistory': typeof UserDashboardLeaveHistoryRoute
  '/admin/adminDashboard/employees': typeof AdminAdminDashboardEmployeesRoute
  '/admin/adminDashboard/leaves': typeof AdminAdminDashboardLeavesRoute
  '/admin/adminDashboard/newEmployees': typeof AdminAdminDashboardNewEmployeesRoute
  '/admin/adminDashboard/panel': typeof AdminAdminDashboardPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/userDashboard': typeof UserDashboardRouteWithChildren
  '/admin/adminDashboard': typeof AdminAdminDashboardRouteWithChildren
  '/userDashboard/leaveForm': typeof UserDashboardLeaveFormRoute
  '/userDashboard/leaveHistory': typeof UserDashboardLeaveHistoryRoute
  '/admin/adminDashboard/employees': typeof AdminAdminDashboardEmployeesRoute
  '/admin/adminDashboard/leaves': typeof AdminAdminDashboardLeavesRoute
  '/admin/adminDashboard/newEmployees': typeof AdminAdminDashboardNewEmployeesRoute
  '/admin/adminDashboard/panel': typeof AdminAdminDashboardPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/userDashboard': typeof UserDashboardRouteWithChildren
  '/admin/adminDashboard': typeof AdminAdminDashboardRouteWithChildren
  '/userDashboard/leaveForm': typeof UserDashboardLeaveFormRoute
  '/userDashboard/leaveHistory': typeof UserDashboardLeaveHistoryRoute
  '/admin/adminDashboard/employees': typeof AdminAdminDashboardEmployeesRoute
  '/admin/adminDashboard/leaves': typeof AdminAdminDashboardLeavesRoute
  '/admin/adminDashboard/newEmployees': typeof AdminAdminDashboardNewEmployeesRoute
  '/admin/adminDashboard/panel': typeof AdminAdminDashboardPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/userDashboard'
    | '/admin/adminDashboard'
    | '/userDashboard/leaveForm'
    | '/userDashboard/leaveHistory'
    | '/admin/adminDashboard/employees'
    | '/admin/adminDashboard/leaves'
    | '/admin/adminDashboard/newEmployees'
    | '/admin/adminDashboard/panel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/userDashboard'
    | '/admin/adminDashboard'
    | '/userDashboard/leaveForm'
    | '/userDashboard/leaveHistory'
    | '/admin/adminDashboard/employees'
    | '/admin/adminDashboard/leaves'
    | '/admin/adminDashboard/newEmployees'
    | '/admin/adminDashboard/panel'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/userDashboard'
    | '/admin/adminDashboard'
    | '/userDashboard/leaveForm'
    | '/userDashboard/leaveHistory'
    | '/admin/adminDashboard/employees'
    | '/admin/adminDashboard/leaves'
    | '/admin/adminDashboard/newEmployees'
    | '/admin/adminDashboard/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UserDashboardRoute: typeof UserDashboardRouteWithChildren
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userDashboard': {
      id: '/userDashboard'
      path: '/userDashboard'
      fullPath: '/userDashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/userDashboard/leaveHistory': {
      id: '/userDashboard/leaveHistory'
      path: '/leaveHistory'
      fullPath: '/userDashboard/leaveHistory'
      preLoaderRoute: typeof UserDashboardLeaveHistoryRouteImport
      parentRoute: typeof UserDashboardRoute
    }
    '/userDashboard/leaveForm': {
      id: '/userDashboard/leaveForm'
      path: '/leaveForm'
      fullPath: '/userDashboard/leaveForm'
      preLoaderRoute: typeof UserDashboardLeaveFormRouteImport
      parentRoute: typeof UserDashboardRoute
    }
    '/admin/adminDashboard': {
      id: '/admin/adminDashboard'
      path: '/admin/adminDashboard'
      fullPath: '/admin/adminDashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adminDashboard/panel': {
      id: '/admin/adminDashboard/panel'
      path: '/panel'
      fullPath: '/admin/adminDashboard/panel'
      preLoaderRoute: typeof AdminAdminDashboardPanelRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/admin/adminDashboard/newEmployees': {
      id: '/admin/adminDashboard/newEmployees'
      path: '/newEmployees'
      fullPath: '/admin/adminDashboard/newEmployees'
      preLoaderRoute: typeof AdminAdminDashboardNewEmployeesRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/admin/adminDashboard/leaves': {
      id: '/admin/adminDashboard/leaves'
      path: '/leaves'
      fullPath: '/admin/adminDashboard/leaves'
      preLoaderRoute: typeof AdminAdminDashboardLeavesRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/admin/adminDashboard/employees': {
      id: '/admin/adminDashboard/employees'
      path: '/employees'
      fullPath: '/admin/adminDashboard/employees'
      preLoaderRoute: typeof AdminAdminDashboardEmployeesRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
  }
}

interface UserDashboardRouteChildren {
  UserDashboardLeaveFormRoute: typeof UserDashboardLeaveFormRoute
  UserDashboardLeaveHistoryRoute: typeof UserDashboardLeaveHistoryRoute
}

const UserDashboardRouteChildren: UserDashboardRouteChildren = {
  UserDashboardLeaveFormRoute: UserDashboardLeaveFormRoute,
  UserDashboardLeaveHistoryRoute: UserDashboardLeaveHistoryRoute,
}

const UserDashboardRouteWithChildren = UserDashboardRoute._addFileChildren(
  UserDashboardRouteChildren,
)

interface AdminAdminDashboardRouteChildren {
  AdminAdminDashboardEmployeesRoute: typeof AdminAdminDashboardEmployeesRoute
  AdminAdminDashboardLeavesRoute: typeof AdminAdminDashboardLeavesRoute
  AdminAdminDashboardNewEmployeesRoute: typeof AdminAdminDashboardNewEmployeesRoute
  AdminAdminDashboardPanelRoute: typeof AdminAdminDashboardPanelRoute
}

const AdminAdminDashboardRouteChildren: AdminAdminDashboardRouteChildren = {
  AdminAdminDashboardEmployeesRoute: AdminAdminDashboardEmployeesRoute,
  AdminAdminDashboardLeavesRoute: AdminAdminDashboardLeavesRoute,
  AdminAdminDashboardNewEmployeesRoute: AdminAdminDashboardNewEmployeesRoute,
  AdminAdminDashboardPanelRoute: AdminAdminDashboardPanelRoute,
}

const AdminAdminDashboardRouteWithChildren =
  AdminAdminDashboardRoute._addFileChildren(AdminAdminDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UserDashboardRoute: UserDashboardRouteWithChildren,
  AdminAdminDashboardRoute: AdminAdminDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
