/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserDashboardRouteImport } from './routes/userDashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserDashboardLeaveHistoryRouteImport } from './routes/userDashboard.leaveHistory'
import { Route as UserDashboardLeaveFormRouteImport } from './routes/userDashboard.leaveForm'

const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/userDashboard',
  path: '/userDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardLeaveHistoryRoute =
  UserDashboardLeaveHistoryRouteImport.update({
    id: '/leaveHistory',
    path: '/leaveHistory',
    getParentRoute: () => UserDashboardRoute,
  } as any)
const UserDashboardLeaveFormRoute = UserDashboardLeaveFormRouteImport.update({
  id: '/leaveForm',
  path: '/leaveForm',
  getParentRoute: () => UserDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/userDashboard': typeof UserDashboardRouteWithChildren
  '/userDashboard/leaveForm': typeof UserDashboardLeaveFormRoute
  '/userDashboard/leaveHistory': typeof UserDashboardLeaveHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/userDashboard': typeof UserDashboardRouteWithChildren
  '/userDashboard/leaveForm': typeof UserDashboardLeaveFormRoute
  '/userDashboard/leaveHistory': typeof UserDashboardLeaveHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/userDashboard': typeof UserDashboardRouteWithChildren
  '/userDashboard/leaveForm': typeof UserDashboardLeaveFormRoute
  '/userDashboard/leaveHistory': typeof UserDashboardLeaveHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/userDashboard'
    | '/userDashboard/leaveForm'
    | '/userDashboard/leaveHistory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/userDashboard'
    | '/userDashboard/leaveForm'
    | '/userDashboard/leaveHistory'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/userDashboard'
    | '/userDashboard/leaveForm'
    | '/userDashboard/leaveHistory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UserDashboardRoute: typeof UserDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userDashboard': {
      id: '/userDashboard'
      path: '/userDashboard'
      fullPath: '/userDashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/userDashboard/leaveHistory': {
      id: '/userDashboard/leaveHistory'
      path: '/leaveHistory'
      fullPath: '/userDashboard/leaveHistory'
      preLoaderRoute: typeof UserDashboardLeaveHistoryRouteImport
      parentRoute: typeof UserDashboardRoute
    }
    '/userDashboard/leaveForm': {
      id: '/userDashboard/leaveForm'
      path: '/leaveForm'
      fullPath: '/userDashboard/leaveForm'
      preLoaderRoute: typeof UserDashboardLeaveFormRouteImport
      parentRoute: typeof UserDashboardRoute
    }
  }
}

interface UserDashboardRouteChildren {
  UserDashboardLeaveFormRoute: typeof UserDashboardLeaveFormRoute
  UserDashboardLeaveHistoryRoute: typeof UserDashboardLeaveHistoryRoute
}

const UserDashboardRouteChildren: UserDashboardRouteChildren = {
  UserDashboardLeaveFormRoute: UserDashboardLeaveFormRoute,
  UserDashboardLeaveHistoryRoute: UserDashboardLeaveHistoryRoute,
}

const UserDashboardRouteWithChildren = UserDashboardRoute._addFileChildren(
  UserDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UserDashboardRoute: UserDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
